#!/usr/bin/env python3
"""
Profile Ditto Inference Model Frame Rate

This script measures:
1. Actual FPS of frame generation
2. Consistency of frame timing (jitter)
3. Latency from audio input to first frame
4. Real-time factor (how fast frames are generated vs real-time audio)
5. Frame generation intervals and statistics
"""

import argparse
import time
import numpy as np
from pathlib import Path
import sys

# Add project root to path
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

from stream_pipeline_online import StreamSDK


class FrameRateProfiler:
    def __init__(self):
        self.frame_times = []
        self.frame_indices = []
        self.first_frame_time = None
        self.first_audio_time = None
        self.audio_chunk_times = []

    def on_audio_sent(self, chunk_idx: int):
        """Called when audio chunk is sent to model"""
        current_time = time.time()
        self.audio_chunk_times.append(current_time)

        if self.first_audio_time is None:
            self.first_audio_time = current_time
            print(f"🎤 First audio chunk sent at t=0.000s")

    def on_frame_generated(self, frame_rgb, frame_idx, timestamp):
        """Callback when frame is generated by model"""
        current_time = time.time()
        self.frame_times.append(current_time)
        self.frame_indices.append(frame_idx)

        if self.first_frame_time is None:
            self.first_frame_time = current_time
            latency = current_time - self.first_audio_time if self.first_audio_time else 0
            print(f"🎬 First frame generated at t={latency:.3f}s (latency from first audio)")

        # Print progress every 25 frames
        if len(self.frame_times) % 25 == 0:
            elapsed = current_time - self.first_audio_time if self.first_audio_time else 0
            fps = len(self.frame_times) / elapsed if elapsed > 0 else 0
            print(f"📊 Frame {frame_idx}: {len(self.frame_times)} frames in {elapsed:.2f}s = {fps:.2f} FPS")

    def print_statistics(self):
        """Print comprehensive statistics about frame generation"""
        print("\n" + "="*80)
        print("FRAME GENERATION STATISTICS")
        print("="*80)

        if len(self.frame_times) < 2:
            print("⚠️ Not enough frames to calculate statistics")
            return

        # Convert to numpy arrays for easier calculation
        frame_times = np.array(self.frame_times)
        frame_indices = np.array(self.frame_indices)

        # Time from first audio to first frame (startup latency)
        startup_latency = self.first_frame_time - self.first_audio_time if self.first_audio_time else 0

        # Overall timing
        total_duration = frame_times[-1] - frame_times[0]
        num_frames = len(frame_times)

        # Frame intervals (time between consecutive frames)
        frame_intervals = np.diff(frame_times)

        # Expected interval for 25 FPS (40ms)
        expected_interval_25fps = 1.0 / 25.0

        # Real-time factor
        # At 25 FPS, we should generate 25 frames per second
        # If we generate slower, RTF < 1.0 (bad - can't keep up with real-time)
        # If we generate faster, RTF > 1.0 (good - can process ahead)
        avg_fps = num_frames / total_duration if total_duration > 0 else 0
        real_time_factor = avg_fps / 25.0

        print(f"\n📈 OVERALL METRICS:")
        print(f"   Total frames generated: {num_frames}")
        print(f"   Total duration: {total_duration:.3f}s")
        print(f"   Average FPS: {avg_fps:.2f}")
        print(f"   Real-time factor: {real_time_factor:.3f}x")
        if real_time_factor < 1.0:
            print(f"   ⚠️ WARNING: Real-time factor < 1.0 means model is TOO SLOW for real-time!")
            print(f"   ⚠️ Model generates {avg_fps:.2f} FPS but needs 25 FPS for real-time playback")
        else:
            print(f"   ✓ Model can keep up with real-time (generates faster than 25 FPS)")

        print(f"\n⏱️ LATENCY:")
        print(f"   Startup latency (audio → first frame): {startup_latency:.3f}s")

        print(f"\n📊 FRAME INTERVAL STATISTICS:")
        print(f"   Expected interval (25 FPS): {expected_interval_25fps*1000:.1f}ms")
        print(f"   Mean interval: {np.mean(frame_intervals)*1000:.1f}ms")
        print(f"   Median interval: {np.median(frame_intervals)*1000:.1f}ms")
        print(f"   Std deviation: {np.std(frame_intervals)*1000:.1f}ms")
        print(f"   Min interval: {np.min(frame_intervals)*1000:.1f}ms")
        print(f"   Max interval: {np.max(frame_intervals)*1000:.1f}ms")

        # Jitter (variation in frame timing)
        jitter = np.std(frame_intervals)
        print(f"\n📉 JITTER (timing consistency):")
        print(f"   Frame timing jitter: {jitter*1000:.1f}ms")
        if jitter > 0.020:  # 20ms
            print(f"   ⚠️ HIGH JITTER: Frame generation is inconsistent!")
            print(f"   ⚠️ This will cause video playback issues")
        else:
            print(f"   ✓ Low jitter - frame generation is consistent")

        # Histogram of frame intervals
        print(f"\n📊 FRAME INTERVAL DISTRIBUTION:")
        bins = [0, 0.020, 0.040, 0.060, 0.080, 0.100, 0.150, 0.200, np.inf]
        bin_labels = ["0-20ms", "20-40ms", "40-60ms", "60-80ms", "80-100ms", "100-150ms", "150-200ms", ">200ms"]
        hist, _ = np.histogram(frame_intervals, bins=bins)

        for label, count in zip(bin_labels, hist):
            percentage = (count / len(frame_intervals)) * 100
            bar = "█" * int(percentage / 2)
            print(f"   {label:12s}: {count:4d} frames ({percentage:5.1f}%) {bar}")

        # Check for problematic intervals (too long)
        slow_frames = frame_intervals > 0.060  # Slower than 60ms (16.7 FPS)
        if np.any(slow_frames):
            num_slow = np.sum(slow_frames)
            print(f"\n⚠️ SLOW FRAMES DETECTED:")
            print(f"   {num_slow} frames took >60ms to generate ({num_slow/len(frame_intervals)*100:.1f}%)")
            print(f"   These frames will cause audio-video desync!")

            # Show worst offenders
            worst_indices = np.argsort(frame_intervals)[-5:][::-1]
            print(f"\n   Top 5 slowest frame generation times:")
            for idx in worst_indices:
                print(f"      Frame {frame_indices[idx]} → {frame_indices[idx+1]}: {frame_intervals[idx]*1000:.1f}ms")

        # Audio chunk analysis
        print(f"\n🎤 AUDIO INPUT STATISTICS:")
        print(f"   Total audio chunks sent: {len(self.audio_chunk_times)}")
        if len(self.audio_chunk_times) > 1:
            audio_duration = self.audio_chunk_times[-1] - self.audio_chunk_times[0]
            print(f"   Audio sending duration: {audio_duration:.3f}s")
            print(f"   Frames per audio chunk: {num_frames / len(self.audio_chunk_times):.2f}")

        print("\n" + "="*80)


def main():
    parser = argparse.ArgumentParser(description="Profile Ditto Inference Frame Rate")
    parser.add_argument("--cfg_pkl", required=True, help="Path to config pickle")
    parser.add_argument("--data_root", required=True, help="Path to model data root")
    parser.add_argument("--source", required=True, help="Path to avatar image")
    parser.add_argument("--audio", required=True, help="Path to audio file (WAV, 16kHz)")
    parser.add_argument("--max_size", type=int, default=1920, help="Max image dimension")
    parser.add_argument("--emo", type=int, default=4, help="Emotion (0-7)")
    parser.add_argument("--num_chunks", type=int, default=20, help="Number of audio chunks to process")

    args = parser.parse_args()

    print("="*80)
    print("DITTO INFERENCE PROFILER")
    print("="*80)
    print(f"Config: {args.cfg_pkl}")
    print(f"Data root: {args.data_root}")
    print(f"Source: {args.source}")
    print(f"Audio: {args.audio}")
    print(f"Processing {args.num_chunks} audio chunks...")
    print("="*80 + "\n")

    # Create profiler
    profiler = FrameRateProfiler()

    # Initialize SDK
    print("Initializing Ditto SDK...")
    sdk = StreamSDK(
        args.cfg_pkl,
        args.data_root,
        max_size=args.max_size,
        emo=args.emo
    )

    # Setup with profiler callback
    sdk.setup(
        args.source,
        output_path=None,
        frame_callback=profiler.on_frame_generated,
        online_mode=True,
        N_d=-1
    )
    print("✓ SDK initialized\n")

    # Load audio
    import librosa
    print(f"Loading audio from {args.audio}...")
    audio, sr = librosa.load(args.audio, sr=16000, mono=True)
    print(f"✓ Loaded {len(audio)} samples at {sr}Hz ({len(audio)/sr:.2f}s)\n")

    # Process audio in chunks
    chunk_size = 6400  # 10 frames * 640 samples = 400ms
    print(f"Processing {args.num_chunks} chunks of {chunk_size} samples ({chunk_size/16000:.3f}s each)...\n")

    start_time = time.time()

    for i in range(args.num_chunks):
        start_idx = i * chunk_size
        end_idx = start_idx + chunk_size

        if end_idx > len(audio):
            print(f"⚠️ Reached end of audio at chunk {i}")
            break

        chunk = audio[start_idx:end_idx]

        # Notify profiler
        profiler.on_audio_sent(i)

        # Send to SDK
        sdk.run_chunk(chunk, chunksize=(3, 5, 2))

        # Small delay to simulate real-time streaming
        # (remove this if you want to measure max throughput)
        # time.sleep(0.4)  # 400ms between chunks

    # Wait a bit for final frames to generate
    print(f"\nWaiting for final frames to generate...")
    time.sleep(2.0)

    end_time = time.time()

    # Print statistics
    profiler.print_statistics()

    print(f"\n⏱️ TOTAL PROCESSING TIME:")
    print(f"   Wall clock time: {end_time - start_time:.3f}s")
    print(f"   Audio duration processed: {args.num_chunks * chunk_size / 16000:.3f}s")
    print(f"   Processing speed: {(args.num_chunks * chunk_size / 16000) / (end_time - start_time):.2f}x real-time")

    # Close SDK
    sdk.close()
    print("\n✓ Profiling complete!")


if __name__ == "__main__":
    main()
