#!/usr/bin/env python3
"""
Avatar Worker - Standalone process that generates and publishes avatar video.

This worker:
1. Connects to a LiveKit room using a provided token
2. Receives TTS audio from the agent via DataStream (data channel)
3. Generates synchronized video using Ditto StreamSDK
4. Publishes both audio and video back to the room

The AvatarRunner handles all synchronization automatically.
"""

import asyncio
import logging
import os
import sys
from pathlib import Path

from livekit import rtc
from livekit.agents import utils
from livekit.agents.voice.avatar import (
    AvatarOptions,
    AvatarRunner,
    DataStreamAudioReceiver,
)

# Add parent directory to path for ditto_video_generator import
sys.path.insert(0, str(Path(__file__).parent))
# Using LiveKit-optimized version with simplified architecture
from ditto_video_generator_decoupled import (
    DittoVideoGeneratorDecoupled as DittoVideoGenerator,
)

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("avatar-worker")

# --- Configuration from environment variables ---
DATA_ROOT = os.environ.get("DATA_ROOT", "./checkpoints/ditto_trt_Ampere_Plus")
CFG_PKL = os.environ.get("CFG_PKL", "./checkpoints/ditto_cfg/v0.4_hubert_cfg_trt.pkl")
SOURCE_PATH = os.environ.get("SOURCE_PATH", "./assets/source_image.png")

AVATAR_WIDTH = int(os.environ.get("AVATAR_WIDTH", "1280"))
AVATAR_HEIGHT = int(os.environ.get("AVATAR_HEIGHT", "720"))
AVATAR_FPS = int(os.environ.get("AVATAR_FPS", "25"))


@utils.log_exceptions(logger=logger)
async def main(api_url: str, api_token: str):
    """
    Main avatar worker function.

    Args:
        api_url: LiveKit server URL (from LIVEKIT_URL env var)
        api_token: Access token for the avatar worker (generated by agent)
    """
    logger.info(f"Avatar worker starting...")
    logger.info(f"Connecting to: {api_url}")
    logger.info(f"Avatar config:")
    logger.info(f"  Source: {SOURCE_PATH}")
    logger.info(f"  Data Root: {DATA_ROOT}")
    logger.info(f"  Resolution: {AVATAR_WIDTH}x{AVATAR_HEIGHT} @ {AVATAR_FPS}fps")

    # Define avatar options
    avatar_options = AvatarOptions(
        video_width=AVATAR_WIDTH,
        video_height=AVATAR_HEIGHT,
        video_fps=AVATAR_FPS,
        audio_sample_rate=16000,  # Ditto expects 16kHz
        audio_channels=1,  # Mono
    )

    # Create Ditto video generator
    logger.info("Initializing Ditto video generator...")
    video_gen = DittoVideoGenerator(
        options=avatar_options,
        data_root=DATA_ROOT,
        cfg_pkl=CFG_PKL,
        source_path=SOURCE_PATH,
    )

    # Connect to the room
    room = rtc.Room()
    await room.connect(api_url, api_token)
    logger.info(f"✅ Connected to room: {room.name}")

    should_stop = asyncio.Event()

    # Handle agent state changes via data channel
    @room.on("data_received")
    def _on_data_received(data: rtc.DataPacket):
        try:
            if data.topic == "agent_state":
                import json

                state_msg = json.loads(data.data.decode("utf-8"))

                if state_msg.get("type") == "agent_state":
                    new_state = state_msg.get("state")
                    old_state = state_msg.get("old_state")

                    logger.info(f"📥 Received agent state: {old_state} → {new_state}")

                    # Update video generator state
                    # video_gen.set_agent_state(new_state)
        except Exception as e:
            logger.error(f"Error handling data packet: {e}", exc_info=True)

    # Stop when agent disconnects or room disconnects
    @room.on("participant_disconnected")
    def _on_participant_disconnected(participant: rtc.RemoteParticipant):
        if participant.kind == rtc.ParticipantKind.PARTICIPANT_KIND_AGENT:
            logger.info(
                f"Agent {participant.identity} disconnected, stopping avatar worker"
            )
            should_stop.set()

    @room.on("disconnected")
    def _on_disconnected():
        logger.info("Room disconnected, stopping avatar worker")
        should_stop.set()

    # Create avatar runner with DataStream audio receiver
    logger.info("Creating AvatarRunner...")
    runner = AvatarRunner(
        room,
        audio_recv=DataStreamAudioReceiver(room),
        video_gen=video_gen,
        options=avatar_options,
    )

    try:
        # Start the avatar runner
        await runner.start()
        logger.info("✅ Avatar runner started - ready to receive audio from agent")

        # Run until stopped or the runner completes/fails
        tasks = [
            asyncio.create_task(runner.wait_for_complete()),
            asyncio.create_task(should_stop.wait()),
        ]
        done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)

        # Check if runner failed
        for task in done:
            if task.exception():
                logger.error(f"Task failed with exception: {task.exception()}")

    finally:
        # Cleanup
        logger.info("Shutting down avatar worker...")
        await utils.aio.cancel_and_wait(*tasks)
        await video_gen.aclose()
        await runner.aclose()
        await room.disconnect()
        logger.info("✅ Avatar worker stopped")


if __name__ == "__main__":
    from livekit.agents.cli.log import setup_logging

    setup_logging("INFO", devmode=True, console=True)

    # Get connection info from environment variables
    livekit_url = os.getenv("LIVEKIT_URL")
    livekit_token = os.getenv("LIVEKIT_TOKEN")

    if not livekit_url or not livekit_token:
        logger.error("❌ LIVEKIT_URL and LIVEKIT_TOKEN must be set")
        logger.error("These are set automatically by the agent worker")
        sys.exit(1)

    # Run the avatar worker
    asyncio.run(main(livekit_url, livekit_token))
